/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "led.h"
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

typedef struct
{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void (*task_handler)(void);

} Task_Control_Block_t;

Task_Control_Block_t user_task[MAX_TASK];
uint32_t current_task = 1; // Start with Task 1
uint32_t g_tick_count = 0;

int main(void)
{
	enable_processor_faults();

	init_scheduler_stack(SCHEDULER_STACK_START);

	init_private_stack();

	init_systick_timer(TICK_HZ);

	switch_MSP_to_PSP();

	led_init_all();

	task1();

    /* Loop forever */
	for(;;);
}

void task1() {
	while(1)
	{
        printf("Task 1 is running\n");
		led_on(LED_GREEN);
		task_delay(1000);
		led_off(LED_GREEN);
		task_delay(1000);
	}
}

void task2() {
	while(1)
	{
        printf("Task 2 is running\n");
		led_on(LED_ORANGE);
		task_delay(500);
		led_off(LED_ORANGE);
		task_delay(500);
	}
}

void task3() {
	while(1)
	{
        printf("Task 3 is running\n");
		led_on(LED_BLUE);
		task_delay(250);
		led_off(LED_BLUE);
		task_delay(250);
	}
}

void task4() {
	while(1)
	{
        printf("Task 4 is running\n");
		led_on(LED_RED);
		task_delay(125);
		led_off(LED_RED);
		task_delay(125);
	}
}

void idle_task()
{
	while(1);
}

void context_switch()
{
	// Pend the PendSV exception
	uint32_t *pICSR = (uint32_t*)(0xE000ED04);
	*pICSR |= (1 << 28);
}

void task_delay(uint32_t tick_count)
{
	// Disable interrupt
	INTERRUPT_DISABLE();

	if (current_task > 0)
	{
		user_task[current_task].block_count = tick_count + g_tick_count;
		user_task[current_task].current_state = TASK_BLOCKED_STATE;
	}
	context_switch();
	// Enable interrupt
	INTERRUPT_ENABLE();
}

void init_systick_timer(uint32_t tick_hz)
{
	uint32_t *pSYST_CSR = (uint32_t*)(0xE000E010);
	uint32_t *pSYST_RVR = (uint32_t*)(0xE000E014);
	uint32_t load_value = (SYSTICK_TIMER_CLK / tick_hz) - 1;

	// Clear the value of SVR
	*pSYST_RVR &= ~(0x00FFFFFF);

	// Load value in to SVR
	*pSYST_RVR |= load_value;

	// Do some settings
	*pSYST_CSR |= (1 << 1); // Enables Systick exception request
	*pSYST_CSR |= (1 << 2); // Indicates the clock source, processor clock source

	// Enable the Systick
	*pSYST_CSR |= (1 << 0);
}

__attribute__((naked)) void init_scheduler_stack(uint32_t scheduler_top_of_stack)
{
	__asm volatile("MSR MSP, %0" : : "r"(scheduler_top_of_stack));
	__asm volatile("BX LR"); // Exit function
}

void init_private_stack()
{
	user_task[0].current_state = TASK_READY_STATE;
	user_task[1].current_state = TASK_READY_STATE;
	user_task[2].current_state = TASK_READY_STATE;
	user_task[3].current_state = TASK_READY_STATE;
	user_task[4].current_state = TASK_READY_STATE;

	user_task[0].psp_value = IDLE_STACK_START;
	user_task[1].psp_value = TASK1_STACK_START;
	user_task[2].psp_value = TASK2_STACK_START;
	user_task[3].psp_value = TASK3_STACK_START;
	user_task[4].psp_value = TASK4_STACK_START;

	user_task[0].task_handler = idle_task;
	user_task[1].task_handler = task1;
	user_task[2].task_handler = task2;
	user_task[3].task_handler = task3;
	user_task[4].task_handler = task4;

	uint32_t *pPSP;
	for (uint32_t i = 0; i < MAX_TASK; i += 1)
	{
		pPSP = (uint32_t*)(user_task[i].psp_value);

		pPSP--;
		*pPSP = DUMMY_XPSR; // 0x0100_0000

		pPSP--;
		*pPSP = (uint32_t)user_task[i].task_handler; // Address code of task

		pPSP--;
		*pPSP = VALUE_LR; // Thread mode + PSP + non-floating-point = 0xFFFFFFFD

		for (uint8_t j = 0; j < 13; j += 1)
		{
			pPSP--;
			*pPSP = 0;
		}

		user_task[i].psp_value = (uint32_t)pPSP;
	}
}

void enable_processor_faults()
{
	uint32_t *pSHCRS = (uint32_t*)(BASE_SHCRS);

	*pSHCRS |= (1 << 16); // MemMange
	*pSHCRS |= (1 << 17); // BusFault
	*pSHCRS |= (1 << 18); // UsageFault
}

uint32_t get_psp_value()
{
	return user_task[current_task].psp_value; // current_task is global variable
}

__attribute__((naked)) void switch_MSP_to_PSP()
{
	// 1. initialize the PSP with TASK1 stack start
	__asm volatile("PUSH {LR}");
	__asm volatile("BL get_psp_value");
	__asm volatile("MSR PSP, R0");
	__asm volatile("POP {LR}");

	// 2. change SP to PSP using CONTROL register
	__asm volatile("MOV R0, #0x02");
	__asm volatile("MSR CONTROL, R0");

	__asm volatile("BX LR"); // Exit function
}

void save_psp_value(uint32_t current_psp_value)
{
	user_task[current_task].psp_value = current_psp_value;
}

void update_next_task()
{
	uint32_t state = TASK_BLOCKED_STATE;
	for (uint32_t i = 0; i < MAX_TASK; i += 1)
	{
		current_task += 1;
		current_task %= MAX_TASK;
		state = user_task[current_task].current_state;
		if (state == TASK_READY_STATE && current_task != 0)
			return;
	}
	current_task = 0;
}

void update_global_tick_count()
{
	g_tick_count += 1;
}

void unblock_task()
{
	for (uint32_t i = 0; i < MAX_TASK; i += 1)
	{
		if (user_task[i].current_state == TASK_BLOCKED_STATE)
		{
			if (user_task[i].block_count <= g_tick_count)
			{
				user_task[i].current_state = TASK_READY_STATE;
			}
		}
	}
}

__attribute__((naked)) void PendSV_Handler()
{
	/* Save the context of current task */
	// 1. Get current running task's PSP value
	__asm volatile("MRS R0, PSP");

	// 2. Using that PSP value store Stack Frame 2 (R4 to R11)
	__asm volatile("STMDB R0!, {R4-R11}");

	// 3. Save the current value of PSP
	__asm volatile("PUSH {LR}");
	__asm volatile("BL save_psp_value");

	/* Retrieve the context of next task */
	// 1. Decide next task to run
	__asm volatile("BL update_next_task");

	// 2. Get its pass PSP value
	__asm volatile("BL get_psp_value");

	// 3. Using that PSP value retrieve Stack Fram 2 (R4 to R11)
	__asm volatile("LDMIA R0!, {R4 - R11}");

	// 4. Update PSP and exit
	__asm volatile("MSR PSP, R0");

	__asm volatile("POP {LR}");
	__asm volatile("BX LR");
}

void SysTick_Handler()
{
	update_global_tick_count();
	unblock_task();
	context_switch();
}

void HardFault_Handler()
{
	printf("Exception: HardFault\n");
	while(1);
}

void MemManage_Handler()
{
	printf("Exception: MemManage\n");
	while(1);
}

void BusFault_Handler()
{
	printf("Exception: BusFault\n");
	while(1);
}

void UsageFault_Handler()
{
	printf("Exception: UsageFault\n");
	while(1);
}
